/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.example;

import  java.util.Map;
import  java.util.List;
import  java.lang.Double;

global List results;

rule "rule-1"
   lock-on-active true
   when
       $map:Map(this.get("RC_NUM")  > 0);
   then
       $map.put("RULE_RES","NOTPASS");
       $map.put("ISELSE", "FALSE");
       update($map);
       System.out.println("Match rule-1.");
              results.add("Match rule-1.");
end
rule "rule-2"
   lock-on-active true
   when
       $map:Map(this["ISELSE"] != "TRUE");
   then
          results.add("Match rule-2.");
       System.out.println("Match rule-2.");
end